import { Category } from '@/types/news';

export interface CategoryDefinition {
  slug: Category;
  label: string;
  description: string;
  keywords: string[];
  icon: string;
}

export const categories: CategoryDefinition[] = [
  {
    slug: 'all',
    label: 'All News',
    description: 'All AI news from every category',
    keywords: [],
    icon: 'Newspaper',
  },
  {
    slug: 'machine-learning',
    label: 'Machine Learning',
    description: 'Latest in ML algorithms, training methods, and frameworks',
    keywords: [
      'machine learning',
      'ml',
      'deep learning',
      'training',
      'dataset',
      'model training',
      'supervised learning',
      'unsupervised learning',
      'reinforcement learning',
      'tensorflow',
      'pytorch',
    ],
    icon: 'Brain',
  },
  {
    slug: 'llms',
    label: 'Large Language Models',
    description: 'News about GPT, Claude, LLaMA, and other language models',
    keywords: [
      'llm',
      'large language model',
      'gpt',
      'chatgpt',
      'claude',
      'llama',
      'gemini',
      'mistral',
      'language model',
      'transformer',
      'chatbot',
      'conversational ai',
      'natural language',
      'nlp',
    ],
    icon: 'MessageSquare',
  },
  {
    slug: 'computer-vision',
    label: 'Computer Vision',
    description: 'Image recognition, object detection, and visual AI',
    keywords: [
      'computer vision',
      'image recognition',
      'object detection',
      'visual',
      'image generation',
      'video analysis',
      'facial recognition',
      'opencv',
      'image processing',
    ],
    icon: 'Eye',
  },
  {
    slug: 'robotics',
    label: 'Robotics',
    description: 'AI-powered robots, automation, and autonomous systems',
    keywords: [
      'robot',
      'robotics',
      'autonomous',
      'automation',
      'self-driving',
      'drone',
      'humanoid',
      'boston dynamics',
      'actuator',
    ],
    icon: 'Bot',
  },
  {
    slug: 'ai-ethics',
    label: 'AI Ethics',
    description: 'Ethics, regulation, bias, and responsible AI development',
    keywords: [
      'ethics',
      'bias',
      'regulation',
      'responsible ai',
      'fairness',
      'transparency',
      'privacy',
      'governance',
      'alignment',
      'safety',
      'ai risk',
      'existential',
    ],
    icon: 'Scale',
  },
  {
    slug: 'generative-ai',
    label: 'Generative AI',
    description: 'AI that creates content - images, music, video, and text',
    keywords: [
      'generative',
      'stable diffusion',
      'midjourney',
      'dall-e',
      'text-to-image',
      'text-to-video',
      'ai art',
      'ai music',
      'content generation',
      'sora',
      'diffusion model',
    ],
    icon: 'Sparkles',
  },
  {
    slug: 'neural-networks',
    label: 'Neural Networks',
    description: 'Architecture innovations and neural network research',
    keywords: [
      'neural network',
      'cnn',
      'rnn',
      'attention mechanism',
      'architecture',
      'backpropagation',
      'layers',
      'neurons',
      'perceptron',
      'activation function',
    ],
    icon: 'Network',
  },
  {
    slug: 'ai-research',
    label: 'AI Research',
    description: 'Academic papers, breakthroughs, and research findings',
    keywords: [
      'research',
      'paper',
      'arxiv',
      'breakthrough',
      'study',
      'scientists',
      'researchers',
      'published',
      'findings',
      'benchmark',
      'state-of-the-art',
    ],
    icon: 'FlaskConical',
  },
  {
    slug: 'ai-business',
    label: 'AI Business',
    description: 'AI industry news, startups, funding, and enterprise adoption',
    keywords: [
      'startup',
      'funding',
      'investment',
      'enterprise',
      'business',
      'revenue',
      'valuation',
      'acquisition',
      'partnership',
      'market',
      'industry',
      'company',
    ],
    icon: 'TrendingUp',
  },
  {
    slug: 'ai-tools',
    label: 'AI Tools',
    description: 'New AI tools, platforms, and developer resources',
    keywords: [
      'tool',
      'platform',
      'api',
      'sdk',
      'framework',
      'library',
      'open source',
      'developer',
      'plugin',
      'integration',
      'workflow',
      'productivity',
    ],
    icon: 'Wrench',
  },
];

export function getCategoryBySlug(slug: Category): CategoryDefinition | undefined {
  return categories.find((cat) => cat.slug === slug);
}

export function getCategoryLabel(slug: Category): string {
  const category = getCategoryBySlug(slug);
  return category?.label ?? 'All News';
}
